name: tekartik_firebase_flutter
description: Firebase flutter
version: 0.8.2
publish_to: none
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2_3
    version: '>=0.6.0'
  firebase_core: '>=0.5.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  process_run:
  dev_test:
  tekartik_app_lints_flutter:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart2_3
      path: app_lints
    version: '>=0.1.0'