name: tekartik_firebase_flutter
description: Firebase flutter
version: 0.8.4+1
publish_to: none
environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart3a
    version: '>=0.9.1'
  firebase_core: '>=0.5.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  process_run: ">=1.2.1+1"
  dev_build: ">=1.1.0+2"
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      ref: dart3a
      path: packages/lints_flutter
    version: '>=0.1.0'

dependency_overrides:
#  tekartik_firebase:
#    path: ../../firebase.dart/firebase
