name: tekartik_all_firebase_flutter_repo
description: Repo
version: 0.1.0
homepage: https://www.example.com
author: alex <alex@tekartik.com>
deploy_to: none

environment:
  sdk: '>=2.5.0 <3.0.0'

dev_dependencies:
  tekartik_travis_ci_flutter:
    git:
      url: git://github.com/tekartik/travis_ci_flutter.dart
      ref: dart2
    version: '>=0.1.0'
  process_run: '>=0.10.0'
# include all from git so that it makes a dependency check
  tekartik_app_emit:
    git:
      url: git://github.com/tekartik/app_common_utils.dart
      ref: dart2
      path: app_emit

dependency_overrides:
# tmp
#  process_run:
#    path: ../process_run.dart