name: tekartik_firebase_auth_flutter
description: Firebase auth flutter
version: 0.10.0
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  tekartik_firebase_auth:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth
      ref: dart3a
    version: '>=0.9.0'
  tekartik_firebase_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      path: firebase_flutter
      ref: dart3a
    version: '>=0.4.0+0'
  firebase_auth: '>=4.11.1'
  google_sign_in: '>=5.4.2'
dev_dependencies:
  flutter_test:
    sdk: flutter
  process_run: '>=0.10.3'
  dev_build:
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      ref: dart3a
      path: packages/lints_flutter
    version: '>=0.1.0'

dependency_overrides:
  tekartik_firebase_flutter:
    path: ../firebase_flutter
