name: tekartik_firebase_auth_flutter
description: Firebase auth flutter
version: 0.10.2
publish_to: none
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  tekartik_firebase_auth:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth
    version: '>=0.9.0'
  tekartik_firebase_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      path: firebase_flutter
    version: '>=0.4.0+0'
  firebase_auth: '>=4.17.6'
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
dev_dependencies:
  flutter_test:
    sdk: flutter
  process_run: ">=1.2.1+1"
  dev_build: ">=1.1.2"
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      path: packages/lints_flutter
    version: '>=0.1.0'
resolution: workspace

