name: tekartik_firebase_firestore_flutter
description: Firebase firestore for flutter
version: 0.11.1
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path:
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart2_3
    version: '>=0.9.0'
  tekartik_firebase_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      path: firebase_flutter
      ref: dart2_3
    version: '>=0.6.0'
  cloud_firestore: '>=4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  process_run: '>=0.10.2'
  tekartik_app_lints_flutter:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart2_3
      path: app_lints
    version: '>=0.1.0'

dependency_overrides:
  tekartik_firebase_flutter:
    path: ../firebase_flutter
