name: tekartik_firebase_firestore_flutter
description: Firebase firestore for flutter
version: 0.11.2
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  path: ">=1.9.0"
  meta: ">=1.15.0"
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
    version: '>=1.1.6'
  tekartik_firebase_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      path: firebase_flutter
    version: '>=0.6.0'
  cloud_firestore: '>=5.6.1'
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase

dev_dependencies:
  flutter_test:
    sdk: flutter
  process_run: ">=1.2.1+1"
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      path: packages/lints_flutter
    version: '>=0.1.0'
resolution: workspace

  #tekartik_firebase_firestore:
  #  path: ../../firebase_firestore.dart/firestore
