name: tekartik_firebase_storage_flutter
description: Firebase storage for flutter
version: 0.8.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path:
  tekartik_firebase_storage:
    git:
      url: git://github.com/tekartik/firebase_storage.dart
      path: storage
      ref: null_safety
    version: '>=0.8.0'
  tekartik_firebase_flutter:
    git:
      url: git://github.com/tekartik/firebase_flutter
      path: firebase_flutter
      ref: null_safety
    version: '>=0.6.0'
  firebase_storage: '>=7.0.0'

dev_dependencies:
  dev_test:
  flutter_test:
    sdk: flutter
  process_run: '>=0.10.2'
  tekartik_app_lints_flutter:
    git:
      url: git://github.com/tekartik/app_flutter_utils.dart
      ref: null_safety
      path: app_lints
    version: '>=0.1.0'

dependency_overrides:
  # pedantic: '>=1.9.0'
  tekartik_firebase_flutter:
    path: ../firebase_flutter